"""recreate_db

Revision ID: 4774ee5edd4f
Revises: 8b35850fad12
Create Date: 2024-01-02 23:22:35.846335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4774ee5edd4f'
down_revision: Union[str, None] = '8b35850fad12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('description', sa.String(length=1500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('pending_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_repr', sa.String(length=100), nullable=False),
    sa.Column('is_username_repr', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'creator', 'client', name='userroles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_repr')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passkey', sa.String(length=228), nullable=False),
    sa.Column('telegram_id', sa.String(length=100), nullable=False),
    sa.Column('telegram_repr', sa.String(length=100), nullable=False),
    sa.Column('is_username_repr', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'creator', 'client', name='userroles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('telegram_repr')
    )
    op.create_table('userdbs_coursedbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coursedb', sa.Integer(), nullable=True),
    sa.Column('userdb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coursedb'], ['courses.id'], name='fk_userdbs_coursedbs_courses_coursedb_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userdb'], ['users.id'], name='fk_userdbs_coursedbs_users_userdb_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdbs_coursedbs')
    op.drop_table('users')
    op.drop_table('pending_users')
    op.drop_table('courses')
    # ### end Alembic commands ###
