"""created

Revision ID: 61e250d33a62
Revises: 24074688f36d
Create Date: 2023-12-16 22:31:41.472055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e250d33a62'
down_revision: Union[str, None] = '24074688f36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passkey', sa.String(length=228), nullable=True),
    sa.Column('telegram_id', sa.String(length=228), nullable=True),
    sa.Column('is_username_id', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'creator', 'client', name='userroles'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passkey'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
