"""made

Revision ID: 959be8a8e56c
Revises: 470145657097
Create Date: 2023-12-19 13:45:14.802669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959be8a8e56c'
down_revision: Union[str, None] = '470145657097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['course_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
