"""added

Revision ID: bc60f697fc7f
Revises: 4774ee5edd4f
Create Date: 2024-01-04 22:54:59.961507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc60f697fc7f'
down_revision: Union[str, None] = '4774ee5edd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('section', 'quiz', 'note_summary', 'flashcard', name='contenttype'), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.course_code'], name='fk_content_courses_course_code_course'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content'], ['content.id'], name='fk_sections_content_id_content'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userdbs_coursedbs')
    op.add_column('courses', sa.Column('department', sa.Integer(), nullable=True))
    op.alter_column('courses', 'course_code',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_unique_constraint(None, 'courses', ['name'])
    op.create_foreign_key('fk_courses_departments_id_department', 'courses', 'departments', ['department'], ['id'])
    op.drop_column('courses', 'id')
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.VARCHAR(length=1500), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('fk_courses_departments_id_department', 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='unique')
    op.alter_column('courses', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)
    op.alter_column('courses', 'course_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('courses', 'department')
    op.create_table('userdbs_coursedbs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coursedb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userdb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coursedb'], ['courses.id'], name='fk_userdbs_coursedbs_courses_coursedb_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userdb'], ['users.id'], name='fk_userdbs_coursedbs_users_userdb_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='userdbs_coursedbs_pkey')
    )
    op.drop_table('sections')
    op.drop_table('content')
    op.drop_table('quizzes')
    op.drop_table('questions')
    op.drop_table('flashcards')
    op.drop_table('departments')
    # ### end Alembic commands ###
